import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getSession } from '@/lib/session'

export async function GET() {
  try {
    const session = await getSession()
    if (!session?.isLoggedIn || !session?.userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const user = await prisma.user.findUnique({
      where: { id: session.userId },
      select: { isSuperAdmin: true, isAdmin: true },
    })

    if (!user?.isSuperAdmin && !user?.isAdmin) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const [
      users,
      products,
      orders,
      topUps,
      settings,
      vpnServers,
      vpnOrders,
      vlessPublicOrders,
      chatMessages,
      referralHistories,
      referralIPTrackings,
      tickets,
      ticketMessages,
      discountEvents,
      serverRevenueLocks,
      resellerProfiles,
      resellerServers,
      resellerOrders,
      withdrawals,
      promoLinks,
      promoActivations,
      ipLogs,
      reviews,
      reviewLikes,
      blockedIps,
      allowedIps,
      apiKeys,
      apiKeyLogs,
      slowReports,
      adminContacts,
      announcements,
      pushSubscriptions,
      notificationLogs,
      blogPosts,
      promoBanners,
      promoPopups,
      luckyWheelPrizes,
      luckyWheelSpins,
      dailyCheckins,
      gifts,
      coupons,
      couponRedemptions,
      notifications,
      ads,
      homepageSections,
      homepageQuickActions,
      homepageStatCards,
      premiumApps,
      premiumAppOrders,
      customPages,
      formSubmissions,
      pageDatabaseRecords,
      siteUpdateLogs,
      v2BoxCodes,
      siteUpdates,
      siteMusics,
      telegramConfigs,
    ] = await Promise.all([
      prisma.user.findMany(),
      prisma.product.findMany(),
      prisma.order.findMany(),
      prisma.topUp.findMany(),
      prisma.settings.findMany(),
      prisma.vpnServer.findMany(),
      prisma.vpnOrder.findMany(),
      prisma.vlessPublicOrder.findMany(),
      prisma.chatMessage.findMany(),
      prisma.referralHistory.findMany(),
      prisma.referralIPTracking.findMany(),
      prisma.ticket.findMany(),
      prisma.ticketMessage.findMany(),
      prisma.discountEvent.findMany(),
      prisma.serverRevenueLock.findMany(),
      prisma.resellerProfile.findMany(),
      prisma.resellerServer.findMany(),
      prisma.resellerOrder.findMany(),
      prisma.withdrawal.findMany(),
      prisma.promoLink.findMany(),
      prisma.promoActivation.findMany(),
      prisma.iPLog.findMany(),
      prisma.review.findMany(),
      prisma.reviewLike.findMany(),
      prisma.blockedIP.findMany(),
      prisma.allowedIP.findMany(),
      prisma.apiKey.findMany(),
      prisma.apiKeyLog.findMany(),
      prisma.slowReport.findMany(),
      prisma.adminContact.findMany(),
      prisma.announcement.findMany(),
      prisma.pushSubscription.findMany(),
      prisma.notificationLog.findMany(),
      prisma.blogPost.findMany(),
      prisma.promoBanner.findMany(),
      prisma.promoPopup.findMany(),
      prisma.luckyWheelPrize.findMany(),
      prisma.luckyWheelSpin.findMany(),
      prisma.dailyCheckin.findMany(),
      prisma.gift.findMany(),
      prisma.coupon.findMany(),
      prisma.couponRedemption.findMany(),
      prisma.notification.findMany(),
      prisma.ad.findMany(),
      prisma.homepageSection.findMany(),
      prisma.homepageQuickAction.findMany(),
      prisma.homepageStatCard.findMany(),
      prisma.premiumApp.findMany(),
      prisma.premiumAppOrder.findMany(),
      prisma.customPage.findMany(),
      prisma.formSubmission.findMany(),
      prisma.pageDatabaseRecord.findMany(),
      prisma.siteUpdateLog.findMany(),
      prisma.v2BoxCode.findMany(),
      prisma.siteUpdate.findMany(),
      prisma.siteMusic.findMany(),
      prisma.telegramConfig.findMany(),
    ])

    const exportData = {
      _meta: {
        exportedAt: new Date().toISOString(),
        version: '1.0',
        source: 'simonvpn-export',
      },
      users,
      products,
      orders,
      topUps,
      settings,
      vpnServers,
      vpnOrders,
      vlessPublicOrders,
      chatMessages,
      referralHistories,
      referralIPTrackings,
      tickets,
      ticketMessages,
      discountEvents,
      serverRevenueLocks,
      resellerProfiles,
      resellerServers,
      resellerOrders,
      withdrawals,
      promoLinks,
      promoActivations,
      ipLogs,
      reviews,
      reviewLikes,
      blockedIps,
      allowedIps,
      apiKeys,
      apiKeyLogs,
      slowReports,
      adminContacts,
      announcements,
      pushSubscriptions,
      notificationLogs,
      blogPosts,
      promoBanners,
      promoPopups,
      luckyWheelPrizes,
      luckyWheelSpins,
      dailyCheckins,
      gifts,
      coupons,
      couponRedemptions,
      notifications,
      ads,
      homepageSections,
      homepageQuickActions,
      homepageStatCards,
      premiumApps,
      premiumAppOrders,
      customPages,
      formSubmissions,
      pageDatabaseRecords,
      siteUpdateLogs,
      v2BoxCodes,
      siteUpdates,
      siteMusics,
      telegramConfigs,
    }

    const counts = Object.fromEntries(
      Object.entries(exportData).filter(([k]) => k !== '_meta').map(([k, v]) => [k, (v as any[]).length])
    )

    return NextResponse.json({ success: true, data: exportData, counts })
  } catch (error: any) {
    console.error('Export error:', error)
    return NextResponse.json({ error: error?.message || 'Export failed' }, { status: 500 })
  }
}
